### ISSUE TITLE
Folder+Subfolder Import

### ISSUE THREAD

**Issue by simhavaktra** [ciur/papermerge#165] opened 2020-10-14 00:34 UTC
Papermerge has been an amazing DMS for our home office!

That said, we have an existing multi-level existing folder structure we can't seem to import. The importer seems to treat subfolders as "not a file". E.x.: [2020-10-14 00:33:17,956: WARNING/ForkPoolWorker-2] Skipping /mnt/media/importer_dir/Scans as it is not a file

Is there a way for us to import/drop in a full existing folder structure without having to import a single directory at a time? I've digged through the documents for several days to no avail, so I apologize if I'm missing something obvious!

**Comment by ciur** [comment] 2020-10-14 09:51
@simhavaktra, thank for opening this issue!
It does not look like big deal to fix this. I will have a look and come back with mode details.

**Comment by doughnet** [comment] 2021-02-05 15:19
Any update on when this being integrated/setup?

**Comment by ciur** [comment] 2021-02-05 15:34
This issue went into oblivion. As I mentioned above not a big deal to fix. I will mark it as part next upcoming release as a reminder to include it in 2.0.

**Comment by bdurrer** [comment] 2021-07-04 20:30
This would be so nice to have, possibly even use the [sub]folder as a tag or metadata

**Comment by christianreiss** [comment] 2022-02-07 12:11
... one year later ...

**Comment by ciur** [comment] 2022-02-07 20:09
This issue is a duplicate of papermerge/papermerge-core#13
As described in above mentioned ticket, requested functionality will be added as 3rd party application which will use currently developed feature of RESTful API to import documents by preserving their folder structure.

**Comment by ciur** [comment] 2023-01-01 12:59
Recursive folder import is now available via [papermerge-cli import /path/to/some/folder](https://docs.papermerge.io/Command%20Line%20Utilities/cli.html#import-folders-documents) command line utility.

**Closed** 2023-01-01 13:02 UTC
Labels: enhancement, feature request

**Comment by doughnet** [comment] 2023-01-03 04:27
> Recursive folder import is available via [papermerge-cli import /path/to/some/folder](https://docs.papermerge.io/Command%20Line%20Utilities/cli.html#import-folders-documents) command line utility.

why do the docs not reference what container papermerge-cli should be executed on? seems lame to recommend using docker for testing and the docs don't provide details how to do things with docker.
