### ISSUE TITLE
Upload of filenames containing accents not working

### ISSUE THREAD

**Issue by Goliath67** [ciur/papermerge#188] opened 2020-10-22 09:36 UTC
I would think this problem is papermerge rather than the docker image so I am submitting the issue here

**Description**
I am living in France so many filenames use é, è, à etc as accented characters.
Files are not uploaded if the filename contains accented characters.
Is this related to the use of SQLite (default) or other?

**Info:**
 - OS: [e.g. Synology NAS DSM with Docker image]
 - Browser [chrome, firefox]
-  Database [SQLite]
 - Papermerge Version [1.5.0]

**Comment by ciur** [comment] 2020-10-23 05:04
Hi @Goliath67, thank you for opening this issue.
 Application definitely works with Russian cyrillic and I saw it managed to upload (on demo site) even filenames with Japanese characters - thus it sounds unlikely to have a problem specifically with french accented characters.
I would help to investigate your issue if you can mention filename or (even better) a sample of problematic file.

**Comment by Goliath67** [comment] 2020-10-23 07:43
Hi,
I just tried uploading the file to the demo website and it does indeed work correctly!
So would it be a problem because of using SQLite (default install) rather than MariaDB?
Or is it a problem I should rather transfer to the docker image github page?

**Comment by ciur** [comment] 2020-10-23 08:09
SQLite by default works with character UTF-8 encodings as expected (i.e. works with french é, è, à characters).
My suggestion is to open a bug to whatever docker image provider you use (or whomever packages Papermerge application for you).

**Comment by Goliath67** [comment] 2020-10-23 10:28
OK Many thanks.

**Comment by l4rm4nd** [comment] 2020-11-29 17:25
Same issue for German umlauts. File can be uploaded, but PDF rendering breaks.

https://github.com/linuxserver/docker-papermerge/issues/16#issuecomment-735427190

**Comment by ciur** [comment] 2021-02-22 14:09
@l4rm4nd  is still the case? I saw that ticket was closed on linuxserver's side. It is ok to close the ticket here as well?

**Comment by l4rm4nd** [comment] 2021-02-22 14:18
Seems to be fixed for Papermerge 1.5.5. Cannot reproduce the previous issues.

![image](https://user-images.githubusercontent.com/21357789/108720437-17e22800-7521-11eb-95f6-71821b7d634a.png)

**Comment by l4rm4nd** [comment] 2021-02-22 14:19
> @l4rm4nd is still the case? I saw that ticket was closed on linuxserver's side. It is ok to close the ticket here as well?
> 
> imho this issue is related to docker packaging, has nothing to do with application code.

Seems to be fixed in Papermerge 1.5.5. Cannot reproduce the previous issues.

![image](https://user-images.githubusercontent.com/21357789/108720671-655e9500-7521-11eb-9dba-9f2a205160d7.png)

**Comment by ciur** [comment] 2021-02-22 17:23
@l4rm4nd thanks!

**Closed by ciur** 2021-02-22 17:23 UTC
Labels: bug
