### ISSUE TITLE
Cannot delete document

### ISSUE THREAD

**Issue by Perry3D** [ciur/papermerge#264] opened 2020-12-21 17:42 UTC
**Description**
I have a document in my inbox which came in by the imap import. I tried to delete it but it doesn't' disappear. 

**Expected**
Document should disappear after deleting.

**Actual**
All i see is an error message in the log of the docker container:
```
papermerge_app | [Mon Dec 21 17:35:25.529934 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934] ERROR:django.request:Internal Server Error: /nodes/
papermerge_app | [Mon Dec 21 17:35:25.530004 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934] Traceback (most recent call last):
papermerge_app | [Mon Dec 21 17:35:25.530008 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]   File "/opt/app/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 243, in _commit
papermerge_app | [Mon Dec 21 17:35:25.530011 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]     return self.connection.commit()
papermerge_app | [Mon Dec 21 17:35:25.530013 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934] psycopg2.errors.ForeignKeyViolation: update or delete on table "core_basetreenode" violates foreign key constraint "core_access_node_id_611e027b_fk_core_basetreenode_id" on table "core_access"
papermerge_app | [Mon Dec 21 17:35:25.530016 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934] DETAIL:  Key (id)=(113) is still referenced from table "core_access".
papermerge_app | [Mon Dec 21 17:35:25.530018 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]
papermerge_app | [Mon Dec 21 17:35:25.530020 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]
papermerge_app | [Mon Dec 21 17:35:25.530022 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934] The above exception was the direct cause of the following exception:
papermerge_app | [Mon Dec 21 17:35:25.530024 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]
papermerge_app | [Mon Dec 21 17:35:25.530026 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934] Traceback (most recent call last):
papermerge_app | [Mon Dec 21 17:35:25.530028 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]   File "/opt/app/.venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
papermerge_app | [Mon Dec 21 17:35:25.530030 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]     response = get_response(request)
papermerge_app | [Mon Dec 21 17:35:25.530032 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]   File "/opt/app/.venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
papermerge_app | [Mon Dec 21 17:35:25.530034 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]     response = self.process_exception_by_middleware(e, request)
papermerge_app | [Mon Dec 21 17:35:25.530036 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]   File "/opt/app/.venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
papermerge_app | [Mon Dec 21 17:35:25.530038 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
papermerge_app | [Mon Dec 21 17:35:25.530040 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]   File "/opt/app/papermerge/core/views/decorators.py", line 39, in inner
papermerge_app | [Mon Dec 21 17:35:25.530042 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]     ret = func(*args, **kwargs)
papermerge_app | [Mon Dec 21 17:35:25.530044 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]   File "/opt/app/.venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
papermerge_app | [Mon Dec 21 17:35:25.530047 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]     return view_func(request, *args, **kwargs)
papermerge_app | [Mon Dec 21 17:35:25.530049 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]   File "/opt/app/papermerge/core/views/nodes.py", line 221, in nodes_view
papermerge_app | [Mon Dec 21 17:35:25.530051 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]     recursive_delete(queryset)
papermerge_app | [Mon Dec 21 17:35:25.530053 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]   File "/opt/app/papermerge/core/models/utils.py", line 38, in recursive_delete
papermerge_app | [Mon Dec 21 17:35:25.530055 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]     node.delete()
papermerge_app | [Mon Dec 21 17:35:25.530069 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]   File "/opt/app/.venv/lib/python3.8/site-packages/mptt/models.py", line 1053, in delete
papermerge_app | [Mon Dec 21 17:35:25.530071 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]     return super(MPTTModel, self).delete(*args, **kwargs)
papermerge_app | [Mon Dec 21 17:35:25.530074 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]   File "/opt/app/.venv/lib/python3.8/site-packages/django/db/models/base.py", line 941, in delete
papermerge_app | [Mon Dec 21 17:35:25.530076 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]     return collector.delete()
papermerge_app | [Mon Dec 21 17:35:25.530078 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]   File "/opt/app/.venv/lib/python3.8/site-packages/django/db/models/deletion.py", line 337, in delete
papermerge_app | [Mon Dec 21 17:35:25.530080 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]     signals.post_delete.send(
papermerge_app | [Mon Dec 21 17:35:25.530082 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]   File "/opt/app/.venv/lib/python3.8/site-packages/django/db/transaction.py", line 232, in __exit__
papermerge_app | [Mon Dec 21 17:35:25.530084 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]     connection.commit()
papermerge_app | [Mon Dec 21 17:35:25.530086 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]   File "/opt/app/.venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
papermerge_app | [Mon Dec 21 17:35:25.530088 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]     return func(*args, **kwargs)
papermerge_app | [Mon Dec 21 17:35:25.530090 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]   File "/opt/app/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 267, in commit
papermerge_app | [Mon Dec 21 17:35:25.530092 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]     self._commit()
papermerge_app | [Mon Dec 21 17:35:25.530094 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]   File "/opt/app/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 243, in _commit
papermerge_app | [Mon Dec 21 17:35:25.530096 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]     return self.connection.commit()
papermerge_app | [Mon Dec 21 17:35:25.530098 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]   File "/opt/app/.venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
papermerge_app | [Mon Dec 21 17:35:25.530100 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]     raise dj_exc_value.with_traceback(traceback) from exc_value
papermerge_app | [Mon Dec 21 17:35:25.530102 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]   File "/opt/app/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 243, in _commit
papermerge_app | [Mon Dec 21 17:35:25.530104 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]     return self.connection.commit()
papermerge_app | [Mon Dec 21 17:35:25.530106 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934] django.db.utils.IntegrityError: update or delete on table "core_basetreenode" violates foreign key constraint "core_access_node_id_611e027b_fk_core_basetreenode_id" on table "core_access"
papermerge_app | [Mon Dec 21 17:35:25.530109 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934] DETAIL:  Key (id)=(113) is still referenced from table "core_access".
papermerge_app | [Mon Dec 21 17:35:25.530111 2020] [wsgi:error] [pid 91:tid 140253696673536] [remote 172.23.0.3:32934]
```

**Info:**
 - Ubuntu 20.04 LTS
 - Firefox
-  Database is the default one from the 1.4 docker-compose file
 - Papermerge Version: 1.5.2

**Comment by Perry3D** [comment] 2020-12-21 17:48
I think the document doesn't exist anymore. I cannot open it and the preview is also not available.
And i can delete other documents.
![image](https://user-images.githubusercontent.com/986287/102806422-1bd8b900-43bd-11eb-9369-ddbabf789764.png)

**Comment by ciur** [comment] 2020-12-22 06:25
@Perry3D, did you add some access permissions that document?

**Comment by Perry3D** [comment] 2020-12-22 08:32
I don't think so. But i am not 100% sure.

Btw i use version 1.5.3 but the interface shows 1.5.2.

**Comment by o---** [comment] 2021-02-25 20:47
I am also having an issue with deleting documents. But I am not sure if the issue is the same. When I try to delete a document and check the browser debug messages, I see :

`XHRPOST http://192.168.1.10/nodes/`
`[HTTP/1.1 500 Internal Server Error 80ms]`
    `PermissionError at /nodes/`
    `[Errno 13] Permission denied: 'page-1.hocr'`
    `Request Method: POST`
    `Request URL: http://192.168.1.10/nodes/`
`Django Version: 3.0.10`
`Python Executable: /opt/papermerge/.venv//bin/python`
`Python Version: 3.7.3`

This is a brand new setup (not docker). Version 1.5.5

Opening the url http://192.168.1.10/nodes/ in browser gives me:
`{"msg": "OK"}`

Besides of that there is an error:

`Uncaught TypeError: t.responseJSON is undefined`
`http://192.168.1.10/static/admin/js/papermerge.js:54`
`http://192.168.1.10/static/admin/js/papermerge.js:25`

**Comment by o---** [comment] 2021-02-25 20:53
And my problem is already resolved by changing the owner on file system level. The question that remains is, why were some folders owned by **root**? I guess its because of the worker process running under **root**?

**Closed** 2024-01-15 06:30 UTC
Labels: bug, confirmed
