### ISSUE TITLE
File Drag & Drop

### ISSUE THREAD

**Issue by hactar** [ciur/papermerge#109] opened 2020-09-04 23:50 UTC
Selecting a file, cut, opening the folder, paste is cumbersome. Being able to drag files into folders would improve ux. Dragging tags into files or files onto tags when this feature comes would be nice too.

**Comment by ciur** [comment] 2020-09-05 06:12
@hactar, good point! I will keep it in mind!

**Comment by ciur** [comment] 2022-07-31 14:19
Duplicate of #445. Feature was implemented and available in [2.1.0a35](https://github.com/papermerge/papermerge-core/pkgs/container/papermerge/30997992?tag=2.1.0a35)

Drag 'n drop quick demo:
[drag-n-drop-demo.webm](https://user-images.githubusercontent.com/24827601/182030687-d2ae33bc-9832-4ba9-a394-a5c6e599086b.webm)

**Closed** 2022-07-31 14:30 UTC
Labels: enhancement
