### ISSUE TITLE
Renaming files change other filenames aswell

### ISSUE THREAD

**Issue by Greenlander92** [ciur/papermerge#223] opened 2020-11-22 14:37 UTC
**Description**
The build in renaming functionality doesn't work for me correctly. I got several .pdf-files in a single Folder. Renaming a file will change the name of every other file which was renamed before. 

**Expected**
Renaming a file should just have an effect of the selected files and not on every file that was renamed with a previous action.

**Actual**
When I rename the first document it works as expected. But renaming another file to a different name will also alter the name of the previously renamed file. Same for the next file wich will also rename all previously renamed files. It's as if the other files are still selected, which they are not. Even when going out of the folder and in again this behaviour stays.

**Info:**
 - OS: Unraid 6.8.3
 - Browser: Firefox
-  Database: SQLite
 - Papermerge Version: 1.5.0

**Comment by ciur** [comment] 2020-11-22 16:04
> The build in renaming functionality

What exactly you mean with "The build  in renaming" ?

**Comment by Greenlander92** [comment] 2020-11-22 22:29
Maybe I missed a hyphen there. I mean the build-in renaming functionality (anklicken des Dokuments und Umbenennen über das Aktionsmenü)

I will test it tomorrow on your demo instance if I don't forget.

**Comment by Greenlander92** [comment] 2020-11-23 18:14
> Can you please confirm that same behaviour is on [demo](https://demo.papermerge.com/)?

Alright. I just tested and confirmed the same behaviour on your test instance. I kept the 6 pdf-files uploaded so you can confirm it yourself.

Steps to reproduce:
- Browse to /F_Test/P_Test/K_Test
- Select the file 1.pdf (doesn't matter if with grid or list view)
- Click on Action -> Rename
- Name it test1.pdf
- Select the file 2.pdf (the renamed file should be visually deselected)
- Click on Action -> Rename
- Name it test2.pdf
-> Both file are named test2.pdf now

I noticed that if you close the session and login again the issue is gone. At least for the first file. If you rename a 2nd file it's the same behaviour.

**Comment by ciur** [comment] 2020-11-23 19:05
@Greenlander92, thank you for detailed steps!
I was able to reproduce it :partying_face: 
I will fix it and make fix available as part of next 1.5.1 version

**Comment by cnbhl** [comment] 2021-04-28 11:01
I was able to reproduce this for folders as well. With the exact steps @Greenlander92 was mentioning:

Steps to reproduce:

* Browse to /Folder1/
* Select the folder "Folder 1.1" (doesn't matter if with grid or list view)
* Click on Action -> Rename
* Name it "Folder 1.4"
* Select the folder "Folder 1.2" (the renamed file should be visually deselected)
* Click on Action -> Rename
* Name it "Folder 9.9"
-> Both folder are named "Folder 9.9" now

**Comment by moscado** [comment] 2022-01-17 11:08
I experienced the bug in the current version 2.0.1. Any plans on when it gets fixed?

**Comment by ciur** [comment] 2022-01-26 19:48
The thing is I split the application in two parts - [backend](https://github.com/papermerge/papermerge-core) and [frontend](https://github.com/papermerge/papermerge.js). This bug described here is on the javascript side. However frontend/javascript side was completely rewritten and buggy behavior is not there any more  - at very least is not there in development version of the frontend.

My plan is to help you to migrate to newer version of the application (featuring new frontend) as soon as it will be out.
The development is very slow, because, as I mentioned, I rewrote the entire frontend and it took me some time to figure out how to do it correctly.

**Comment by ciur** [comment] 2024-02-04 06:01
I am closing this issue as it is not relevant for 3.0.3.

**Closed by ciur** 2024-02-04 06:01 UTC
Labels: bug
