### ISSUE TITLE
Update Docker to 2.0.0.rc35

### ISSUE THREAD

**Issue by w4tzmann** [ciur/papermerge#312] opened 2021-02-25 18:17 UTC
Description
Changed the papermerge images flages from 'latest' to '2.0.0.rc35'. After starting the containers again, i receive Server Error (500).
db container logs:

```
2021-02-25 17:59:45.746 UTC [43] ERROR:  column core_user.role_id does not exist at character 276


2021-02-25 17:59:45.746 UTC [43] STATEMENT:  SELECT "core_user"."id", "core_user"."password", "core_user"."last_login", "core_user"."is_superuser", "core_user"."username", "core_user"."first_name", "core_user"."last_name", "core_user"."email", "core_user"."is_staff", "core_user"."is_active", "core_user"."date_joined", "core_user"."role_id", "core_user"."created_at", "core_user"."updated_at" FROM "core_user" WHERE "core_user"."id" = 1 LIMIT 21

2021-02-25 17:59:48.468 UTC [44] ERROR:  column core_page.hocr_step_0 does not exist at character 304

2021-02-25 17:59:48.468 UTC [44] STATEMENT:  SELECT "core_page"."id", "core_page"."document_id", "core_page"."user_id", "core_page"."number", "core_page"."page_count", "core_page"."text", "core_page"."norm_doc_title", "core_page"."norm_folder_title", "core_page"."norm_breadcrump", "core_page"."norm_text", "core_page"."lang", "core_page"."image", "core_page"."hocr_step_0", "core_page"."hocr_step_1", "core_page"."hocr_step_2", "core_page"."hocr_step_3" FROM "core_page" WHERE "core_page"."document_id" = 7 ORDER BY "core_page"."number" AS
```

papermerge_worker log:
```
psycopg2.errors.UndefinedColumn: column core_page.hocr_step_0 does not exist

LINE 1: ...m_text", "core_page"."lang", "core_page"."image", "core_page...

                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/opt/app/.venv/lib/python3.8/site-packages/celery/app/trace.py", line 405, in trace_task

    R = retval = fun(*args, **kwargs)

  File "/opt/app/.venv/lib/python3.8/site-packages/celery/app/trace.py", line 697, in __protected_call__

    return self.run(*args, **kwargs)

  File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/management/commands/worker.py", line 30, in txt2db

    doc.update_text_field()

  File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/models/document.py", line 728, in update_text_field

    for page in self.pages.all():

  File "/opt/app/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 287, in __iter__

    self._fetch_all()

  File "/opt/app/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all

    self._result_cache = list(self._iterable_class(self))

  File "/opt/app/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__

    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)

  File "/opt/app/.venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql

    cursor.execute(sql, params)

  File "/opt/app/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute

    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

  File "/opt/app/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/opt/app/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

  File "/opt/app/.venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/opt/app/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

django.db.utils.ProgrammingError: column core_page.hocr_step_0 does not exist

LINE 1: ...m_text", "core_page"."lang", "core_page"."image", "core_page...

                                                             ^
```
**Expected**
Login page without error

**Actual**
Website response with Server Error 500 -Looks for me like there was no update for the db schema.

**Info:**
 - OS: Docker on Debian
 - Browser Edge
-  Database PostgreSQL 12.3
 - Papermerge Version 1.5.5 to 2.0.0.rc35

**Comment by ciur** [comment] 2021-02-26 07:14
@w4tzmann, thank you for reporting this. I will fix it.

**Comment by ciur** [comment] 2021-02-26 09:29
I close this issue as duplicate of #311.

**Closed by ciur** 2021-02-26 09:29 UTC
Labels: bug, docker

**Comment by yieldhog** [comment] 2021-02-27 16:09
I am getting this same problem with a fresh installation (Linuxserver latest image). It looks as if others are having the same problem. An issue has been opened with linuxserver.

https://www.reddit.com/r/Papermerge/comments/ls7dq3/new_update_broke_my_instance_docker/

**Comment by ciur** [comment] 2021-02-27 16:20
yes, there is an issue with upgrading from 1.5.x to 2.0.0. I [fixed](https://github.com/papermerge/papermerge-core/commit/bf90d59578fde2fd54ec68220efd139ca008dd6f) it and tomorrow I will release next release candidate.

**Comment by yieldhog** [comment] 2021-02-27 17:46
@ciur,

Thanks, appreciate your work on this -- excited to check it out. Just an FYI, if feedback is helpful at all, this was a new (fresh) installation, not an upgrade.
