### ISSUE TITLE
2 folders, different metadata, getting crossed

### ISSUE THREAD

**Issue by jjkonway** [ciur/papermerge#259] opened 2020-12-19 02:30 UTC
Hello, I am fairly new to django and js, i appreciate this awesome project and the community behind it. ..I am having this issue, any suggestions? 

papermerge 1.5.3 , running via gunicorn/nginx 

**Description**
I have two folders with different metadata. When i open up folder 1, then go back and open folder 2, and then go back to folder 1. The metadata of folder 2 and 1 get mixed and both are being displayed. 

**Info:**
 - OS: [e.g. Windows 10, Ubuntu 20.04 LTS]
-  Database [SQLite, PostgreSQL 12.1]
 - Papermerge Version [e.g. 1.4.3]

**Comment by ciur** [comment] 2020-12-19 11:32
@jjkonway, sounds like a bug :+1:  I will fix it, thanks for heads-up!

**Comment by ciur** [comment] 2021-03-01 11:18
Duplicate of #310

**Closed by ciur** 2021-03-01 11:18 UTC
Labels: approved, bug
