### ISSUE TITLE
New action to reprocess documents

### ISSUE THREAD

**Issue by dani** [ciur/papermerge#180] opened 2020-10-18 09:53 UTC
Right now, documents are only processed on initial import, and automates only applies when the document is imported in the Inbox. This is by design and is fine.

But it would be useful to reprocess existing documents (OCR + Automates). Eg, maybe I uploaded it with the wrong OCR lang set. Or I just added a bunch of new automates and I'd like them to be applied to existing docs instead of  setting new tags manually.

**Comment by ciur** [comment] 2020-10-18 17:07
@dani, thank you for opening this issue. It makes total sense to have a "restart OCR/Automate". I will take care of it.

**Comment by amo13** [comment] 2020-11-13 23:05
duplicate of #180

**Comment by ciur** [comment] 2021-01-21 11:32
The automation part (re-run of automation) is implemented as part of Papermerge 2.0 and will be available in couple of weeks.

The document re-processing (the OCR part) is little trickier with introduction of document versioning:
 on document re-processing should new version be added or should new document with different language overwrite/reset all existing document versions ?
I close this issue as the most stringent problem (re-run of automations) was solved.

**Closed by ciur** 2021-01-21 11:32 UTC
Labels: enhancement, feature request
